# cotire.cmake 1.7.9 generated file
# C:/Users/unknown/source/repos/interlunar/source/src/cml/cml_ORIGINAL_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "C:/Users/unknown/source/repos/interlunar/source/src/cmake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.9")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "-j")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_MEMORY_SCALING_FACTOR "170")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "CMAKE_INTDIR=\"Debug\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_MINSIZEREL "CMAKE_INTDIR=\"MinSizeRel\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "CMAKE_INTDIR=\"Release\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELWITHDEBINFO "CMAKE_INTDIR=\"RelWithDebInfo\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "/W3;/GR;/EHsc;/Zi;/MTd;/Zi;/Ob0;/Od;/RTC1")
set (COTIRE_TARGET_COMPILE_FLAGS_MINSIZEREL "/W3;/GR;/EHsc;/Zi;/MT;/O1;/Ob1")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "/W3;/GR;/EHsc;/Zi;/MT;/O2;/Ob2")
set (COTIRE_TARGET_COMPILE_FLAGS_RELWITHDEBINFO "/W3;/GR;/EHsc;/Zi;/MT;/Zi;/O2;/Ob1")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "C:/Users/unknown/source/repos/interlunar/source/src")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "500")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "C:/Users/unknown/source/repos/interlunar/source/src/cml/source/CMLexicalAnalyzer.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/CodePageConversion.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/FileInfo.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/LibPak.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MArchive.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MAsyncHttp.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MBlobArray.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MCRC32.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MChunkReWriter.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MClipboard.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MCrashDump.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MCsvParser.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MDataChecker.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MDebug.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MDebugNew.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MFile.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MHttpSpooler.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MInet.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MLex.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MLocale.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MMatrix.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MPageArray.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MPdb.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MProcess.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MProcessController.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MProfiler.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MRegistry.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MSmartRefresh.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MSocket.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MStateMachine.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MStrEx.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MSync.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MThread.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MTime.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MTraceMemory.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MUrl.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MUtil.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MVK.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MVector3.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MXml.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MZFile.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MZFileSystem.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/MZip.cpp;C:/Users/unknown/source/repos/interlunar/source/src/cml/source/SafeString.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (MSVC "1")
set (CMAKE_GENERATOR "Visual Studio 15 2017")
set (CMAKE_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (CMAKE_CXX_COMPILER_ID "MSVC")
set (CMAKE_CXX_COMPILER_VERSION "19.16.27045.0")
set (CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
