# cotire.cmake 1.7.9 generated file
# C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/RealSpace2_ORIGINAL_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "C:/Users/unknown/source/repos/interlunar/source/src/cmake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.9")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "-j")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_MEMORY_SCALING_FACTOR "170")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "CMAKE_INTDIR=\"Debug\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;_USE_GDIPLUS")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_MINSIZEREL "CMAKE_INTDIR=\"MinSizeRel\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;_USE_GDIPLUS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "CMAKE_INTDIR=\"Release\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;_USE_GDIPLUS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELWITHDEBINFO "CMAKE_INTDIR=\"RelWithDebInfo\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;_USE_GDIPLUS;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "/W3;/GR;/EHsc;/Zi;/MTd;/Zi;/Ob0;/Od;/RTC1")
set (COTIRE_TARGET_COMPILE_FLAGS_MINSIZEREL "/W3;/GR;/EHsc;/Zi;/MT;/O1;/Ob1")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "/W3;/GR;/EHsc;/Zi;/MT;/O2;/Ob2")
set (COTIRE_TARGET_COMPILE_FLAGS_RELWITHDEBINFO "/W3;/GR;/EHsc;/Zi;/MT;/Zi;/O2;/Ob1")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "C:/Users/unknown/source/repos/interlunar/source/src")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "500")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/BulletCollision.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/ColorTypes.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/EluLoader.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/LightmapGenerator.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/MeshManager.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/PostProcess.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RAStar.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RAniEventInfo.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RAnimation.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RAnimationFile.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RAnimationMgr.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RAnimationNode.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RBaseTexture.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RBoundary.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RBspObject.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RBspObjectDrawD3D9.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RBspObjectDrawVulkan.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RCamera.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RCharCloth.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RCloth.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RCollisionDetection.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RCylinder.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RDummyList.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RDynamicLight.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RError.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RFont.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RFrameWork.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RHalfEdgeMesh.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RLenzFlare.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RLightList.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMaterialList.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMath.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMesh.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMeshMgr.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMeshNode.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMeshNodeData.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMeshNodeStringTable.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMeshUtil.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMesh_Frame.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMesh_Load.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMesh_Mtrl.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMesh_Render.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RMtrl.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RNavigationMesh.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RNavigationNode.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/ROcclusionList.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RParticleSystem.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RRoam.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RS2Vulkan.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RShaderMgr.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RSolidBsp.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RSphere.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RToken.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RVisualMesh.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RVisualMeshMgr.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RVisualMeshUtil.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/RealSpace2.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/Renderer.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/ShaderUtil.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/TextureLoader.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/VulkanMaterial.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/XMLParser.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/rmatrix.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/rquaternion.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/rvector.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/stdafx.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/vulkan_functions.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/vulkandebug.cpp;C:/Users/unknown/source/repos/interlunar/source/src/RealSpace2/Source/vulkantools.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (MSVC "1")
set (CMAKE_GENERATOR "Visual Studio 15 2017")
set (CMAKE_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (CMAKE_CXX_COMPILER_ID "MSVC")
set (CMAKE_CXX_COMPILER_VERSION "19.16.27045.0")
set (CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
