INSERT INTO Item (ItemID, Name) Values (1, '구식 단검')
INSERT INTO Item (ItemID, Name) Values (2, '구식 카타나')
INSERT INTO Item (ItemID, Name) Values (11, '철제 단검')
INSERT INTO Item (ItemID, Name) Values (12, '철제 카타나')
INSERT INTO Item (ItemID, Name) Values (4001, '랩터 50')
INSERT INTO Item (ItemID, Name) Values (4002, '랩터 50 x2')
INSERT INTO Item (ItemID, Name) Values (4003, '랩터 120')
INSERT INTO Item (ItemID, Name) Values (4004, '랩터 120 x2')
INSERT INTO Item (ItemID, Name) Values (4005, '미닉 567')
INSERT INTO Item (ItemID, Name) Values (4006, '미닉 567 x2')
INSERT INTO Item (ItemID, Name) Values (4007, '자우르스 A')
INSERT INTO Item (ItemID, Name) Values (4008, '자우르스 A x2')
INSERT INTO Item (ItemID, Name) Values (5001, '레너드')
INSERT INTO Item (ItemID, Name) Values (5002, '레너드 x2')
INSERT INTO Item (ItemID, Name) Values (5003, '월콤 S5')
INSERT INTO Item (ItemID, Name) Values (5004, '월콤 S5 x2')
INSERT INTO Item (ItemID, Name) Values (6001, '브레이커 3')
INSERT INTO Item (ItemID, Name) Values (6002, '브레이커 5')
INSERT INTO Item (ItemID, Name) Values (6003, '브레이커 6')
INSERT INTO Item (ItemID, Name) Values (7001, '니코 R2')
INSERT INTO Item (ItemID, Name) Values (7002, '니코 R5')
INSERT INTO Item (ItemID, Name) Values (7003, '월콤 워리어 77')
INSERT INTO Item (ItemID, Name) Values (7004, '맥스웰 LX30')
INSERT INTO Item (ItemID, Name) Values (8001, '니코 MG-K8')
INSERT INTO Item (ItemID, Name) Values (9001, '월콤 L1')
INSERT INTO Item (ItemID, Name) Values (21001, '아레스 런닝셔츠 A')
INSERT INTO Item (ItemID, Name) Values (21002, '르노 면셔츠 A')
INSERT INTO Item (ItemID, Name) Values (21003, '베니코 가죽코트 A')
INSERT INTO Item (ItemID, Name) Values (21004, '빈츠 겨울철 자켓 A')
INSERT INTO Item (ItemID, Name) Values (21005, '미즈 가죽코트 A')
INSERT INTO Item (ItemID, Name) Values (21501, '플렉스 면티셔츠 A')
INSERT INTO Item (ItemID, Name) Values (21502, '유라이크 가죽자켓 A')
INSERT INTO Item (ItemID, Name) Values (21503, '렉스 군용조끼 A')
INSERT INTO Item (ItemID, Name) Values (21504, '아로나 가죽자켓 A')
INSERT INTO Item (ItemID, Name) Values (21505, 'L* 가죽코트 A')
INSERT INTO Item (ItemID, Name) Values (22001, '빈츠 방한 장갑 A')
INSERT INTO Item (ItemID, Name) Values (22002, '미즈 가죽장갑 A')
INSERT INTO Item (ItemID, Name) Values (22003, '아레스 철제장갑 A')
INSERT INTO Item (ItemID, Name) Values (22501, '아로나 가죽장갑 A')
INSERT INTO Item (ItemID, Name) Values (22502, '렉스 철제장갑 A')
INSERT INTO Item (ItemID, Name) Values (22503, 'L* 가죽장갑 A')
INSERT INTO Item (ItemID, Name) Values (23001, '빈츠 트레이닝 바지 A')
INSERT INTO Item (ItemID, Name) Values (23002, '르노 활동성 바지 A')
INSERT INTO Item (ItemID, Name) Values (23003, '미즈 가죽 바지 A')
INSERT INTO Item (ItemID, Name) Values (23004, '베니코 대님바지 A')
INSERT INTO Item (ItemID, Name) Values (23501, '플렉스 트레이닝 바지 A')
INSERT INTO Item (ItemID, Name) Values (23502, '아로나 여성용 청바지 A')
INSERT INTO Item (ItemID, Name) Values (23503, '렉스 군용바지 A')
INSERT INTO Item (ItemID, Name) Values (23504, 'L* 블랙 면바지 A')
INSERT INTO Item (ItemID, Name) Values (24001, '빈츠 캐쥬얼 슈즈 A')
INSERT INTO Item (ItemID, Name) Values (24002, '베니코 캐쥬얼 슈즈 A')
INSERT INTO Item (ItemID, Name) Values (24003, '르노 등산용 신발 A')
INSERT INTO Item (ItemID, Name) Values (24004, '아레스 철제신발 A')
INSERT INTO Item (ItemID, Name) Values (24501, '유라이크 가죽구두')
INSERT INTO Item (ItemID, Name) Values (24502, '아로나 가죽구두')
INSERT INTO Item (ItemID, Name) Values (24503, 'L* 가죽부츠')
INSERT INTO Item (ItemID, Name) Values (24504, '렉스 철제신발 A')
INSERT INTO Item (ItemID, Name) Values (30001, '의료킷 MK-1')
INSERT INTO Item (ItemID, Name) Values (30101, '수리킷 MK-1')
INSERT INTO Item (ItemID, Name) Values (30201, '카녹스 FB1')
INSERT INTO Item (ItemID, Name) Values (30301, '카녹스 FG1')
INSERT INTO Item (ItemID, Name) Values (30401, '카녹스 SG1')
