#pragma once

#include <string>
#include "MZFileSystem.h"

#define MATCHNOTIFY_NETWORK_CREATE_FAILED	10
#define MATCHNOTIFY_NETWORK_PORTINUSE		11
#define MATCHNOTIFY_NETWORK_NAT_ESTABLISH	15
#define MATCHNOTIFY_GENERAL_USER_NOTFOUND	51
#define MATCHNOTIFY_CHARACTER_NOT_EXIST		70
#define MATCHNOTIFY_STAGE_ALREADY_EXIST		100
#define MATCHNOTIFY_STAGE_NOT_EXIST			101
#define MATCHNOTIFY_STAGE_TEAMFULL			110
#define MATCHNOTIFY_CHATROOM_CREATE_SUCCEED	150
#define MATCHNOTIFY_CHATROOM_CREATE_FAILED	151
#define MATCHNOTIFY_CHATROOM_ALREADY_EXIST	152
#define MATCHNOTIFY_CHATROOM_NOT_EXIST		153
#define MATCHNOTIFY_CHATROOM_NOT_USING		154
#define MATCHNOTIFY_CHATROOM_JOIN_FAILED	155
#define MATCHNOTIFY_CHATROOM_USER_FULL		156
#define MATCHNOTIFY_GAME_SPEEDHACK			200
#define MATCHNOTIFY_GAME_MEMORYHACK			201
#define MATCHNOTIFY_FRIEND_ALREADY_EXIST	251
#define MATCHNOTIFY_FRIEND_NOT_EXIST		252
#define MATCHNOTIFY_FRIEND_TOO_MANY_ADDED	253
#define MATCHNOTIFY_FRIEND_ADD_SUCCEED		255
#define MATCHNOTIFY_FRIEND_REMOVE_SUCCEED	256
#define MATCHNOTIFY_USER_WHISPER_REJECTED	301
#define MATCHNOTIFY_USER_WHISPER_IGNORED	302
#define MATCHNOTIFY_USER_INVITE_REJECTED	311
#define MATCHNOTIFY_USER_INVITE_IGNORED		312

bool InitializeNotify(MZFileSystem *pfs);
bool NotifyMessage(int nMsgID, std::string *out);
bool NotifyMessage(int nMsgID, char* Output, size_t OutputSize);
template <size_t Size> bool NotifyMessage(int nMsgID, char(&Output)[Size]) {
	return NotifyMessage(nMsgID, Output, Size); }