# cotire.cmake 1.7.9 generated file
# C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/CSCommon_ORIGINAL_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "C:/Users/unknown/source/repos/interlunar/source/src/cmake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.9")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "-j")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_MEMORY_SCALING_FACTOR "170")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "CMAKE_INTDIR=\"Debug\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_MINSIZEREL "CMAKE_INTDIR=\"MinSizeRel\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "CMAKE_INTDIR=\"Release\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELWITHDEBINFO "CMAKE_INTDIR=\"RelWithDebInfo\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "/W3;/GR;/EHsc;/Zi;/MTd;/Zi;/Ob0;/Od;/RTC1")
set (COTIRE_TARGET_COMPILE_FLAGS_MINSIZEREL "/W3;/GR;/EHsc;/Zi;/MT;/O1;/Ob1")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "/W3;/GR;/EHsc;/Zi;/MT;/O2;/Ob2")
set (COTIRE_TARGET_COMPILE_FLAGS_RELWITHDEBINFO "/W3;/GR;/EHsc;/Zi;/MT;/Zi;/O2;/Ob1")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "C:/Users/unknown/source/repos/interlunar/source/src")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "500")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/AnimationStuff.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/BasicInfo.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/BasicInfoHistory.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/HitRegistration.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MAgentObject.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MBaseChannelRule.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MBaseGameType.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MBaseLocale.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MBaseQuest.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MBaseStringResManager.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MChattingFilter.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCommand.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCommandBuilder.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCommandCommunicator.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCommandManager.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCommandParameter.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCommandProfiler.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MCustomClient.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MLadderStatistics.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchGameType.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchItem.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchNotify.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchStageSetting.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchTransDataType.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchUtil.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MMatchWorldItemDesc.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MObject.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MPacket.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MPacketCrypter.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MQuestDropTable.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MQuestFormula.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MQuestItem.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MQuestMap.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MQuestNPC.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MServer.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MSharedCommandTable.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MSurvivalMap.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MTCPSocket.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MUID.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/MXmlParser.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/NetIO.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/Physics.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/RealCPNet.cpp;C:/Users/unknown/source/repos/interlunar/source/src/CSCommon/Source/stuff.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (MSVC "1")
set (CMAKE_GENERATOR "Visual Studio 15 2017")
set (CMAKE_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (CMAKE_CXX_COMPILER_ID "MSVC")
set (CMAKE_CXX_COMPILER_VERSION "19.16.27045.0")
set (CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
