#pragma once

#define CCMD_ID_HELP				1
#define CCMD_ID_WHISPER				2
#define CCMD_ID_REPORT119			3
#define CCMD_ID_FRIEND				4
#define CCMD_ID_CLAN				5
#define CCMD_ID_STAGE_FOLLOW		6
#define CCMD_ID_REQUEST_QUICK_JOIN	7
#define CCMD_ID_EMOTION_TAUNT		8
#define CCMD_ID_EMOTION_BOW			9
#define CCMD_ID_EMOTION_WAVE		10
#define CCMD_ID_EMOTION_LAUGH		11
#define CCMD_ID_EMOTION_CRY			12
#define CCMD_ID_EMOTION_DANCE		13
#define CCMD_ID_MACRO				14
#define CCMD_ID_SUICIDE				15
#define CCMD_ID_CALLVOTE			16
#define CCMD_ID_VOTEYES				17
#define CCMD_ID_VOTENO				18
#define CCMD_ID_KICK				19
#define CCMD_ID_CREATE_CHATROOM		20
#define CCMD_ID_JOIN_CHATROOM		21
#define CCMD_ID_LEAVE_CHATROOM		22
#define CCMD_ID_SELECT_CHATROOM		23
#define CCMD_ID_INVITE_CHATROOM		24
#define CCMD_ID_VISIT_CHATROOM		25
#define CCMD_ID_CHAT_CHATROOM		26

// Player Announce Commands
#define CCMD_ANNOUNCE_FPS			50