# cotire.cmake 1.7.9 generated file
# C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Mint2_ORIGINAL_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "C:/Users/unknown/source/repos/interlunar/source/src/cmake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.9")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "-j")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_MEMORY_SCALING_FACTOR "170")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "CMAKE_INTDIR=\"Debug\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_MINSIZEREL "CMAKE_INTDIR=\"MinSizeRel\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELEASE "CMAKE_INTDIR=\"Release\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_RELWITHDEBINFO "CMAKE_INTDIR=\"RelWithDebInfo\";WIN32;_WINDOWS;_WINSOCK_DEPRECATED_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;NDEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "/W3;/GR;/EHsc;/Zi;/MTd;/Zi;/Ob0;/Od;/RTC1")
set (COTIRE_TARGET_COMPILE_FLAGS_MINSIZEREL "/W3;/GR;/EHsc;/Zi;/MT;/O1;/Ob1")
set (COTIRE_TARGET_COMPILE_FLAGS_RELEASE "/W3;/GR;/EHsc;/Zi;/MT;/O2;/Ob2")
set (COTIRE_TARGET_COMPILE_FLAGS_RELWITHDEBINFO "/W3;/GR;/EHsc;/Zi;/MT;/Zi;/O2;/Ob1")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "C:/Users/unknown/source/repos/interlunar/source/src")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "500")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MAniBmButton.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MAnimation.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBButtonLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBEditLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBFrameLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBGroupLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBLabelLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBListBoxLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBPopupMenu.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBScrollBarLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBSliderLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBTabCtrlLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBTextAreaLook.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBitmap.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBitmapDrawer.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBmButton.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MBmLabel.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MButton.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MButtonGroup.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MComboBox.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MConsoleFrame.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MCursor.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MDragObject.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MDrawContext.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MEdit.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MEvent.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MFileBox.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MFileDialog.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MFont.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MFrame.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MFrameDrawer.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MGroup.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MHotKey.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MHyperText.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MIDLResource.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MLabel.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MListBox.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MMsgBox.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MPanel.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MPicture.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MPopupMenu.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MResourceManager.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MScrollBar.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MSkin.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MSlider.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MStringTable.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MTabCtrl.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MTextArea.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MToolTip.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MTypes.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/MWidget.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/Mint.cpp;C:/Users/unknown/source/repos/interlunar/source/src/Mint2/Source/stdafx.cpp")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (MSVC "1")
set (CMAKE_GENERATOR "Visual Studio 15 2017")
set (CMAKE_CONFIGURATION_TYPES "Debug;Release;MinSizeRel;RelWithDebInfo")
set (CMAKE_CXX_COMPILER_ID "MSVC")
set (CMAKE_CXX_COMPILER_VERSION "19.16.27045.0")
set (CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;mm;CPP")
