// Default Widget Color
#ifndef MCOLORTABLE_H
#define MCOLORTABLE_H

#define DEFCOLOR_NORMAL			0xFFFFB023
#define DEFCOLOR_LIGHT			0xFFF0CB63
#define DEFCOLOR_DARK			0xFFC8960C
#define DEFCOLOR_DISABLE		0xFF808080
#define DEFCOLOR_BACKGROUND		0x77000000

//#define DEFCOLOR_TEXT			0xFFFFFF
#define DEFCOLOR_PEN_HIGHLIGHT	0xFFFFFFFF

// Frame Default
#define DEFCOLOR_FRAME_PLANE		DEFCOLOR_BACKGROUND
#define DEFCOLOR_FRAME_OUTLINE		DEFCOLOR_NORMAL
#define DEFCOLOR_FRAME_TEXT			0xFFFFFFFF

// MLabel
//#define DEFCOLOR_MLABEL_TEXT	DEFCOLOR_NORMAL
#define DEFCOLOR_MLABEL_TEXT			0xFFFFFFFF

// MButton
#define DEFCOLOR_MBUTTON_PLANE		DEFCOLOR_NORMAL
#define DEFCOLOR_MBUTTON_LIGHTPLANE	DEFCOLOR_LIGHT
#define DEFCOLOR_MBUTTON_DARKPLANE	DEFCOLOR_DARK
#define DEFCOLOR_MBUTTON_TEXT		0xFF000000

// MEdit
#define DEFCOLOR_MEDIT_PLANE		DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MEDIT_OUTLINE		DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MEDIT_TEXT			0xFFCDCDCD

// MList
#define DEFCOLOR_MLIST_PLANE			0xFF141414
#define DEFCOLOR_MLIST_OUTLINE			DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MLIST_SELECTEDPLANE	DEFCOLOR_MLIST_OUTLINE
#define DEFCOLOR_MLIST_TEXT				0xFFCDCDCD
#define DEFCOLOR_MLIST_SELECTEDTEXT		DEFCOLOR_MLIST_PLANE

// MScollBar
#define DEFCOLOR_MSCROLLBAR_PLANE		0xFF000000

// MPopup
#define DEFCOLOR_MPOPUP_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MPOPUP_SELECTEDPLANE	DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MPOPUP_TEXT			DEFCOLOR_FRAME_TEXT
#define DEFCOLOR_MPOPUP_SELECTEDTEXT	DEFCOLOR_MPOPUP_PLANE

// ToolTip
#define DEFCOLOR_MTOOLTIP_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MTOOLTIP_OUTLINE		DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MTOOLTIP_TEXT			DEFCOLOR_FRAME_TEXT

// MFrame
#define DEFCOLOR_MFRAME_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_MFRAME_OUTLINE			DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_MMENUBAR_PLANE			DEFCOLOR_NORMAL
#define DEFCOLOR_MMENUBAR_TEXT			0xFF000000

// MPanel
#define DEFCOLOR_MPANEL_PLANE			0x00000000
#define DEFCOLOR_MPANEL_BORDER			DEFCOLOR_NORMAL

#endif